# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataloader/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tickerInput = QtWidgets.QLineEdit(self.centralwidget)
        self.tickerInput.setGeometry(QtCore.QRect(50, 50, 300, 30))
        self.tickerInput.setObjectName("tickerInput")
        self.pathInput = QtWidgets.QLineEdit(self.centralwidget)
        self.pathInput.setGeometry(QtCore.QRect(50, 100, 200, 30))
        self.pathInput.setObjectName("pathInput")
        self.selectPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectPathButton.setGeometry(QtCore.QRect(260, 100, 90, 30))
        self.selectPathButton.setObjectName("selectPathButton")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(130, 150, 140, 40))
        self.downloadButton.setObjectName("downloadButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(50, 200, 300, 30))
        self.statusLabel.setObjectName("statusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YF Dataloader"))
        self.tickerInput.setPlaceholderText(_translate("MainWindow", "Enter Ticker (Eg. QQQ, SCHD)"))
        self.pathInput.setPlaceholderText(_translate("MainWindow", "Enter Saving path (default. C:)"))
        self.selectPathButton.setText(_translate("MainWindow", "Select Path"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.statusLabel.setText(_translate("MainWindow", "Status: 정상"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
